### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'read' with new python docker client version 3.0

### ISSUE THREAD

**Issue by eyenx** [goldmann/docker-squash#158]
Hello 

We use docker-squash on a daily basis to squash our base-images. Today we can't squash the images anymore. We get: 

```
$ docker-squash -t registry.example.com/alpine  registry.exmaple.com/alpine
2018-02-01 06:24:59,601 root         INFO     docker-squash version 1.0.6, Docker c97c6d6, API 1.35...
2018-02-01 06:24:59,602 root         INFO     Using v2 image format
2018-02-01 06:24:59,614 root         INFO     Old image has 4 layers
2018-02-01 06:24:59,615 root         INFO     Checking if squashing is necessary...
2018-02-01 06:24:59,615 root         INFO     Attempting to squash last 4 layers...
2018-02-01 06:24:59,615 root         INFO     Saving image sha256:370c6891b7c58c64a715aaf93f17e1e10c8a4e4e3533e04a0959f1f205756cbe to /tmp/docker-squash-ujuyJb/old directory...
2018-02-01 06:25:00,849 root         ERROR    'generator' object has no attribute 'read'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/docker_squash/image.py", line 321, in _save_image
    with tarfile.open(fileobj=image, mode='r|') as tar:
  File "/usr/lib/python2.7/tarfile.py", line 1705, in open
    t = cls(name, filemode, stream, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1587, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python2.7/tarfile.py", line 2358, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python2.7/tarfile.py", line 1251, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python2.7/tarfile.py", line 579, in read
    buf = self._read(size)
  File "/usr/lib/python2.7/tarfile.py", line 587, in _read
    return self.__read(size)
  File "/usr/lib/python2.7/tarfile.py", line 612, in __read
    buf = self.fileobj.read(self.bufsize)
AttributeError: 'generator' object has no attribute 'read'
```

Docker-squash was installed on our builder Image (docker:latest) by pip:

```
$ pip install docker-squash
Collecting docker-squash
  Downloading docker-squash-1.0.6.tar.gz
Collecting docker (from docker-squash)
  Downloading docker-3.0.0-py2.py3-none-any.whl (120kB)
Collecting six (from docker-squash)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting backports.ssl-match-hostname>=3.5; python_version < "3.5" (from docker->docker-squash)
  Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
Collecting ipaddress>=1.0.16; python_version < "3.3" (from docker->docker-squash)
  Downloading ipaddress-1.0.19.tar.gz
Collecting docker-pycreds>=0.2.1 (from docker->docker-squash)
  Downloading docker_pycreds-0.2.1-py2.py3-none-any.whl
Collecting requests!=2.18.0,>=2.14.2 (from docker->docker-squash)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting websocket-client>=0.32.0 (from docker->docker-squash)
  Downloading websocket_client-0.46.0-py2.py3-none-any.whl (200kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests!=2.18.0,>=2.14.2->docker->docker-squash)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests!=2.18.0,>=2.14.2->docker->docker-squash)
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
Collecting urllib3<1.23,>=1.21.1 (from requests!=2.18.0,>=2.14.2->docker->docker-squash)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
Collecting idna<2.7,>=2.5 (from requests!=2.18.0,>=2.14.2->docker->docker-squash)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Installing collected packages: backports.ssl-match-hostname, ipaddress, six, docker-pycreds, chardet, certifi, urllib3, idna, requests, websocket-client, docker, docker-squash
  Running setup.py install for backports.ssl-match-hostname: started
    Running setup.py install for backports.ssl-match-hostname: finished with status 'done'
  Running setup.py install for ipaddress: started
    Running setup.py install for ipaddress: finished with status 'done'
  Running setup.py install for docker-squash: started
    Running setup.py install for docker-squash: finished with status 'done'
Successfully installed backports.ssl-match-hostname-3.5.0.1 certifi-2018.1.18 chardet-3.0.4 docker-3.0.0 docker-pycreds-0.2.1 docker-squash-1.0.6 idna-2.6 ipaddress-1.0.19 requests-2.18.4 six-1.11.0 urllib3-1.22 websocket-client-0.46.0
```

The only thing that changed from yesterday is the docker python client we are using:

```
Collecting docker (from docker-squash)
  Downloading docker-3.0.0-py2.py3-none-any.whl (120kB)
```

Yesterday it worked, but we were using docker-2.7.0.

Can you look into this?

Thanks

**Comment by hyperknot** [comment]
For anyone running into this: the workaround is to manually install or require `"docker < 3"` in the same pip-install or requirements.txt where docker-squash is installed.

**Comment by goldmann** [comment]
@eyenx thanks for this report. It looks like the API changed again with new version of Python bindings. I'll look into this. Until then, please make sure you have older version of the docker library installed as mentioned by @hyperknot.

**Comment by eyenx** [comment]
Thank you.

**Comment by goldmann** [comment]
This is the main problem: https://github.com/docker/docker-py/commit/388f291b13fca76f4974a1ee89225ff7f3afb85b

**Comment by goldmann** [comment]
I found a blocker to add support for v3 of the library. With the refactoring done to the library, one of the call we use in our tool: `save`, is very slow with v3. The issue is that the stream is now read byte by byte since the [chunk size is set to 1](https://github.com/docker/docker-py/blob/3.0.1-release/docker/api/client.py#L356). A simple busybox image is exported in 10 seconds where it should be done in zero time as it was before. Imagine if you would squash a 2BG image...

I've opened this ticket: https://github.com/docker/docker-py/issues/1905 See also linked issue for similar reports.

My proposal for now is to update requirement to use version < 3.0.0 of the library and leave this open until the upstream client will be fixed.

**Comment by hyperknot** [comment]
Why am I not surprised with Docker and an unstable release...
I actually recommend pinning to 2.x for at least half a year more, for now.

**Comment by rindeal** [comment]
Fix was merged upstream in a 3.1.0 release - https://github.com/docker/docker-py/pull/1906. The API now allows to specify custom chunk size.

**Comment by goldmann** [comment]
@rindeal Yep, I'll use this and add support for 3.x in the squash tool.

**Comment by whummer** [comment]
Any update on this issue @goldmann ? Looks like `docker-squash` still doesn't work with `3.x`. Would be great to see this fixed. Thanks for maintaining this awesome tool, btw!

**Comment by goldmann** [comment]
Oh crap, I totally forgot :( I'll work on this this week!

**Comment by Cryptophobia** [comment]
Thank you for maintaining this awesome tool @goldmann. I ran into this issue today and a successful workaround is to downgrade docker python library back to docker-2.7.0 for now:

```
sudo pip install "docker<3.0.0"
```

**Comment by goldmann** [comment]
This was a long week... :) I'm going to release it today with the fix.

**Comment by goldmann** [comment]
`1.0.7` released, sorry for the delay! https://github.com/goldmann/docker-squash/releases/tag/1.0.7

**Comment by Cryptophobia** [comment]
@goldmann : Awesome!
